/*
	BÀI KIỂM TRA SỐ 2

	Họ và tên:	Nguyễn Văn Hải
	Mã sinh viên:	16T1021039
	Lớp học phần:	Ngôn ngữ truy vấn có cấu trúc (SQL)-Nhóm 1 2019-2020.2.TIN3012.001
*/

/***************************************************************
I.TRUY VẤN
****************************************************************/
-- cÂU 5.1 --
	SELECT * FROM NHACUNGCAP
-- cÂU 5.2 --
	SELECT A.MAHANG,A.TENHANG,A.SOLUONG FROM MATHANG A
-- cÂU 5.3 --
	SELECT CONCAT(NV.HO,' ',NV.TEN ) AS HOTEN,NV.DIACHI,YEAR(NV.NGAYLAMVIEC) AS NAMBATDAULAMVIEC FROM NHANVIEN NV
-- cÂU 5.4 --
	SELECT DIACHI,DIENTHOAI FROM NHACUNGCAP
	WHERE TENGIAODICH = 'A'
-- cÂU 5.5 --
	SELECT MAHANG,TENHANG FROM MATHANG
	WHERE GIAHANG > 6000 AND SOLUONG > 50
-- cÂU 5.6 --
------NGẮN GỌN -----
	SELECT MAHANG,MACONGTY FROM MATHANG
------DÀI DÒNG -------
	SELECT MH.MAHANG,MH.TENHANG,MH.MALOAIHANG,MH.SOLUONG,MH.DONVITINH,MH.GIAHANG,NCC.MACONGTY,NCC.TENCONGTY,NCC.DIACHI,NCC.DIENTHOAI,NCC.FAX,NCC.EMAIL FROM MATHANG MH JOIN NHACUNGCAP NCC ON MH.MACONGTY = NCC.MACONGTY
-- cÂU 5.7 --
-------------KHÔNG BIẾT YÊU CẦU NHỮNG THÔNG TIN GÌ TỪ BẢNG MẶT HÀNG DO CÔNG TY A CUNG CẤP------
	SELECT * FROM MATHANG MH JOIN NHACUNGCAP NCC ON MH.MACONGTY = NCC.MACONGTY
	WHERE NCC.TENCONGTY = 'Công ty A'
-- cÂU 5.8 --
	SELECT NCC.MACONGTY,NCC.TENCONGTY,NCC.DIACHI FROM MATHANG MH JOIN NHACUNGCAP NCC ON MH.MACONGTY = NCC.MACONGTY
	WHERE MH.MALOAIHANG = '1' -----MÃ 1 LÀ NHỮNG LOẠI HÀNG THỰC PHẨM
-- cÂU 5.9 --
----- H06 MÃ HÀNG CỦA MẶT HÀNG OMO -----------------
--------------- SELECT * FROM CHITIETDATHANG -------------
	SELECT KH.TENGIAODICH FROM KHACHHANG KH JOIN DONDATHANG DH ON KH.MAKHACHHANG = DH.MAKHACHHANG
							   JOIN CHITIETDATHANG CTDH ON DH.SOHOADON = CTDH.SOHOADON
	WHERE CTDH.MAHANG = 'H06'
-- CÂU 5.10 --
--------- SELECT * FROM NHANVIEN ---------
	SELECT TOP(1) * FROM DONDATHANG
-- cÂU 5.11 --
	SELECT NV.MANHANVIEN,CONCAT(NV.HO,' ',NV.TEN ) AS HOTEN,NV.LUONGCOBAN,NV.PHUCAP,(NV.LUONGCOBAN + ISNULL(NV.PHUCAP,0)) AS LUONG FROM NHANVIEN NV
-- cÂU 5.12 --
---- CHƯA HIỂU CÂU HỎI LẮM,ĐƠN ĐẶT HÀNG SỐ 3 LÀ SỐ HÓA ĐƠN THỨ 3 HAY SỐ HÓA ĐƠN BẰNG 3,Ở ĐÂY EM LÀM SỐ HÓA ĐƠN BẰNG 3
	--SELECT * FROM DONDATHANG
	SELECT *,((CT.SOLUONG*CT.GIABAN)-(CT.SOLUONG*CT.GIABAN*MUCGIAMGIA/100)) TIENTRA FROM CHITIETDATHANG AS CT
	WHERE SOHOADON = '3'
-- cÂU 5.13 --
	SELECT KH.* FROM KHACHHANG KH JOIN NHACUNGCAP NCC ON KH.TENGIAODICH = NCC.TENGIAODICH
-- cÂU 5.14 --
---- EM KHÔNG RÕ Ý CỦA CÂU HỎI NÀY -- CÂU NÀY EM SELECT RA NGÀY SINH CỦA CÁC NHÂN VIÊN CÓ SẮP XẾP NHỮNG NHÂN VIÊN CÓ CÙNG NGÀY SINH SẼ NẰM GẦN NHAU
	SELECT NV.MANHANVIEN,CONCAT(NV.HO,' ',NV.TEN ) AS HOTEN,DAY(NV.NGAYSINH) AS NGAYSINH FROM NHANVIEN NV 
	ORDER BY NGAYSINH
-- cÂU 5.15 --
	SELECT KH.* FROM KHACHHANG KH JOIN DONDATHANG DH ON KH.DIACHI = DH.NOIGIAOHANG
-- cÂU 5.16 --
	SELECT KH.TENCONGTY,KH.TENGIAODICH,KH.DIACHI,KH.DIENTHOAI,NCC.TENCONGTY,NCC.TENGIAODICH,NCC.DIACHI,NCC.DIENTHOAI
			 FROM KHACHHANG KH JOIN DONDATHANG DH ON KH.MAKHACHHANG = DH.MAKHACHHANG
							   JOIN CHITIETDATHANG CTDH ON DH.SOHOADON = CTDH.SOHOADON
							   JOIN MATHANG MH ON CTDH.MAHANG = MH.MAHANG
							   JOIN NHACUNGCAP NCC ON MH.MACONGTY = NCC.MACONGTY
-- CÂU 5.20 -- 
-- Tổng số tiền phải trả cho mỗi đơn hàng
	SELECT KH.MAKHACHHANG,DDH.SOHOADON,CTDH.MAHANG,CTDH.GIABAN,CTDH.SOLUONG,CTDH.MUCGIAMGIA,((CTDH.GIABAN * CTDH.SOLUONG)-((CTDH.GIABAN * CTDH.SOLUONG)*(ISNULL(CTDH.MUCGIAMGIA,0))/100)) AS TIENTRA 
	FROM CHITIETDATHANG CTDH JOIN DONDATHANG DDH ON CTDH.SOHOADON = DDH.SOHOADON
									  JOIN KHACHHANG KH ON KH.MAKHACHHANG = DDH.MAKHACHHANG
	GROUP BY KH.MAKHACHHANG,DDH.SOHOADON,CTDH.MAHANG,CTDH.GIABAN,CTDH.SOLUONG,CTDH.MUCGIAMGIA
	ORDER BY MAKHACHHANG

--
	SELECT KH.MAKHACHHANG,DDH.SOHOADON,SUM(SOLUONG*GIABAN - SOLUONG*MUCGIAMGIA*GIABAN/100) 
	FROM CHITIETDATHANG CTDH JOIN DONDATHANG DDH ON CTDH.SOHOADON = DDH.SOHOADON
									  JOIN KHACHHANG KH ON KH.MAKHACHHANG = DDH.MAKHACHHANG
	GROUP BY KH.MAKHACHHANG,DDH.SOHOADON
	ORDER BY MAKHACHHANG
-- CÂU : 21 --
-- TRONG NĂM 2017 NHỮNG MẶT HÀNG NÀO ĐẶT MUA ĐÚNG 1 LẦN
	SELECT DDH.SOHOADON,MH.MAHANG,MH.TENHANG
	FROM MATHANG MH JOIN CHITIETDATHANG CTDH ON MH.MAHANG = CTDH.MAHANG
					JOIN DONDATHANG DDH ON CTDH.SOHOADON = DDH.SOHOADON
	WHERE YEAR(NGAYDATHANG) = 2017
	GROUP BY DDH.SOHOADON,MH.MAHANG,MH.TENHANG
	HAVING COUNT(MH.MAHANG) = 1
-- CÂU 22 --

	 