SELECT SV.MASV,SV.HODEM,SV.TEN,DT.DIEMLAN1,DT.DIEMLAN2,MH.SODVHT,ISNULL(DT.DIEMLAN1,0)+ISNULL(DT.DIEMLAN2,0)/2 AS DIEMTHI
FROM SINHVIEN SV JOIN DIEMTHI DT ON SV.MASV = DT.MASV JOIN MONHOC MH ON DT.MAMONHOC = MH.MAMONHOC
GROUP BY SV.MASV,SV.HODEM,SV.TEN,DT.DIEMLAN1,DT.DIEMLAN2,MH.SODVHT
